version: "3"

services:
  mc:
    container_name: mc-paper
    image: itzg/minecraft-server:java16-openj9
    ports:
      - 127.0.0.1:25565:25565
    volumes:
      - ./minecraft-paper-data:/data
    tty: true
    stdin_open: true
    restart: unless-stopped
    environment:
      VERSION: 1.17.1
      TYPE: PAPER
      TZ: Asia/Shanghai
      EXEC_DIRECTLY: "true"
      MEMORY: "4G"
      TUNE_VIRTUALIZED: "TRUE"
      TUNE_NURSERY_SIZES: "TRUE"
      EULA: "TRUE"
      #ONLINE_MODE: "FALSE"
      #JVM_OPTS: -javaagent:/data/plugins/authlib-injector.jar=https://littlesk.in/api/yggdrasil
      #OVERRIDE_SERVER_PROPERTIES: "true"
# docs in https://github.com/itzg/docker-minecraft-server
